apiVersion: apps/v1
kind: Deployment
metadata:
  name: kakao
  labels:
    app: kakao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kakao
  template:
    metadata:
      labels:
        app: kakao
    spec:
      containers:
        - name: kakao
          image: admin35.azurecr.io/kakao:latest
          ports:
            - containerPort: 8080
#          env:
#            - name: payurl
#              valueFrom:
#                configMapKeyRef:
#                  name: LANG
#                  key: language
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
#            initialDelaySeconds: 10
#            timeoutSeconds: 2
#            periodSeconds: 5
#            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5