apiVersion: apps/v1
kind: Deployment
metadata:
  name: Kakao
  labels:
    app: Kakao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Kakao
  template:
    metadata:
      labels:
        app: Kakao
    spec:
      containers:
        - name: Kakao
          image: username/Kakao:latest
          ports:
            - containerPort: 8080
          env:
            - name: payurl
              valueFrom:
                configMapKeyRef:
                  name: apipayurl
                  key: url
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5